version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    tty: true
    stdin_open: true
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - bundle_path:/bundle/vendor
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres@db
    depends_on:
      - db
volumes:
  postgres:
  bundle_path: